"""Build the canonical skill tree from a live, working install -- repaired.

Why this exists
---------------
v5.2.5 shipped 5 skills (7 once installed) whose SKILL.md began with a UTF-8
BOM. A strict YAML frontmatter reader sees "\\ufeff---" instead of "---", never
opens the block, and the skill loses its `description`. The description is the
ONLY thing an agent sees when deciding whether to load a skill, so a BOM makes
the skill effectively invisible. Two of the affected skills were
`skyrim-memory` and `skyrim-tool-router` -- the two the workspace instructions
tell every agent to load FIRST.

A second fault rode along: `housecarl`'s description contained mojibake
("a<euro>" for an em dash) from UTF-8 bytes decoded as CP1252 and re-encoded.

Both are PowerShell-generated-file faults, and both are silent. So the build is
no longer "copy the folder" -- it repairs, then refuses to finish if anything is
still broken.

Usage
-----
    python build_canonical_skills.py <live-skills-dir> <output-canonical-dir>
"""
import os
import re
import shutil
import sys

# Files that are machine-specific or build noise and must never be redistributed.
# housecarl.user.json holds the operator's MO2/shim instance dir; skyrim-forge's
# INSTALLATION.json holds discovered tool paths. Both are regenerated by setup.
EXCLUDE_NAMES = {'installation.json', 'housecarl.user.json', '.ds_store', 'thumbs.db'}
EXCLUDE_DIRS = {'.git', 'node_modules', '__pycache__', '.venv',
                # A locally-installed plugin carries its compiled MCP server and
                # a nested copy of its own skills. Neither belongs in a
                # redistributable pack: the binaries are the upstream project's
                # to distribute (houseCARL is GPL-3.0), and the nested skills
                # duplicate the top-level ones. v5 shipped housecarl at 173 KB;
                # copying the live install verbatim made it 48 MB.
                'server', 'bin', 'obj'}
# A nested 'skills' directory inside a skill is the plugin's own bundled copy.
NESTED_DUP_DIRS = {'skills'}
EXCLUDE_SUFFIX = ('.bak', '.tmp', '.log', '.pyc')
# Compiled artefacts are never redistributed by this pack.
BINARY_SUFFIX = ('.dll', '.exe', '.pdb', '.so', '.dylib', '.lib', '.a', '.bin',
                 '.nupkg', '.msi')

# Absolute paths that betray the pack author's machine. The pack's own rule is
# "discover tools, never hardcode a drive letter" -- this enforces it.
MACHINE_PATH_RE = re.compile(
    r'([A-Za-z]:\\Users\\(?!<)[A-Za-z0-9._-]+|[A-Za-z]:\\\\Users\\\\(?!<)[A-Za-z0-9._-]+)',
    re.I)
# Example paths are allowed when clearly marked as examples.
ALLOW_NEAR = ('example', 'e.g.', 'for instance', 'author', 'sample', 'illustrat')

TEXT_EXT = {'.md', '.txt', '.json', '.yaml', '.yml', '.toml', '.py',
            '.ini', '.xml', '.js', '.ts'}

# Scripts Windows executes are copied BYTE-FOR-BYTE and never normalised.
# The BOM rule is inverted for these, which is the trap:
#   SKILL.md  -- a BOM BREAKS it (frontmatter never opens, description lost)
#   .ps1/.bat -- a BOM is REQUIRED unless the file is pure ASCII, because
#                PowerShell 5.1 falls back to the ANSI code page without one,
#                and a single em dash then decodes into a stray quote that
#                breaks the parse ("string is missing the terminator").
# .bat/.cmd additionally want CRLF. So: do not touch them at all.
VERBATIM_EXT = {'.ps1', '.psm1', '.psd1', '.bat', '.cmd'}


# Mojibake alphabet. UTF-8 lead bytes C2-F4 decode under CP1252 to U+00C2-U+00F4;
# continuation bytes 80-BF decode to whatever CP1252 maps them to (five of them --
# 0x81, 0x8D, 0x8F, 0x90, 0x9D -- are undefined and simply never appear).
_LEAD = ''.join(chr(c) for c in range(0xC2, 0xF5))
_CONT = ''
for _b in range(0x80, 0xC0):
    try:
        _CONT += bytes([_b]).decode('cp1252')
    except UnicodeDecodeError:
        pass
MOJI_RUN = re.compile('[%s][%s]{1,3}' % (re.escape(_LEAD), re.escape(_CONT)))


def demojibake(s):
    """Repair UTF-8-read-as-CP1252 damage one RUN at a time.

    Repairing whole-file is wrong: a single legitimate character outside CP1252
    (an arrow, a box-drawing glyph) makes the strict encode throw and the entire
    file silently goes unrepaired. That is exactly how the housecarl description
    kept its mojibake all the way through v5.

    Matching only plausible mojibake runs also means legitimate accented prose is
    never touched: a lone accented letter is not followed by a character from the
    continuation range, so it never matches.
    """
    fixed_any = [False]

    def repair(m):
        run = m.group(0)
        try:
            out = run.encode('cp1252', errors='strict').decode('utf-8', errors='strict')
        except (UnicodeEncodeError, UnicodeDecodeError):
            return run
        fixed_any[0] = True
        return out

    return MOJI_RUN.sub(repair, s), fixed_any[0]

def clean_text(raw_bytes):
    """Return (text, notes) with BOM stripped, mojibake repaired, endings LF."""
    notes = []
    if raw_bytes.startswith(b'\xef\xbb\xbf'):
        raw_bytes = raw_bytes[3:]
        notes.append('BOM')
    txt = raw_bytes.decode('utf-8', errors='replace')
    if '�' in txt:
        notes.append('REPLACEMENT-CHAR')
    txt, fixed = demojibake(txt)
    if fixed:
        notes.append('mojibake')
    new = txt.replace('\r\n', '\n').replace('\r', '\n')
    if new != txt:
        notes.append('CRLF')
    return new, notes


def frontmatter_ok(txt):
    """True if a strict reader can open the block and find a description."""
    m = re.match(r'^---\s*\n(.*?)\n---\s*\n', txt, re.S)
    if not m:
        return False, 'no frontmatter block'
    if not re.search(r'^description:\s*\S', m.group(1), re.M):
        return False, 'no description'
    return True, ''


def machine_paths(txt):
    out = []
    for line in txt.splitlines():
        for m in MACHINE_PATH_RE.finditer(line):
            low = line.lower()
            if any(a in low for a in ALLOW_NEAR):
                continue
            out.append((m.group(0), line.strip()[:110]))
    return out


def main():
    src, dst = sys.argv[1], sys.argv[2]
    if os.path.isdir(dst):
        shutil.rmtree(dst)
    os.makedirs(dst)

    repaired, copied, skipped = [], 0, []
    bad_frontmatter, leaks = [], []

    for sk in sorted(os.listdir(src)):
        s_dir = os.path.join(src, sk)
        if not os.path.isdir(s_dir):
            continue
        for dp, dirs, fs in os.walk(s_dir):
            dirs[:] = [d for d in dirs if d.lower() not in EXCLUDE_DIRS
                       and not (dp == s_dir and d.lower() in NESTED_DUP_DIRS)]
            for f in sorted(fs):
                if f.lower().endswith(BINARY_SUFFIX):
                    skipped.append(os.path.relpath(os.path.join(dp, f), src))
                    continue
                if f.lower() in EXCLUDE_NAMES or f.lower().endswith(EXCLUDE_SUFFIX):
                    skipped.append(os.path.relpath(os.path.join(dp, f), src))
                    continue
                sp = os.path.join(dp, f)
                rel = os.path.relpath(sp, src)
                op = os.path.join(dst, rel)
                os.makedirs(os.path.dirname(op), exist_ok=True)
                ext = os.path.splitext(f)[1].lower()
                if ext in VERBATIM_EXT or ext not in TEXT_EXT:
                    # Windows-executed scripts and binaries: byte-for-byte.
                    # Stripping a .ps1's BOM makes PowerShell 5.1 decode it as
                    # ANSI and can break the parse outright.
                    shutil.copy2(sp, op)
                    copied += 1
                    continue
                txt, notes = clean_text(open(sp, 'rb').read())
                if notes:
                    repaired.append((rel, notes))
                with open(op, 'w', encoding='utf-8', newline='\n') as fh:
                    fh.write(txt)
                copied += 1
                if f.lower() == 'skill.md':
                    ok, why = frontmatter_ok(txt)
                    if not ok:
                        bad_frontmatter.append((rel, why))
                for hit, line in machine_paths(txt):
                    leaks.append((rel, hit, line))

    print('canonical build: %d files written, %d machine/noise files skipped'
          % (copied, len(skipped)))
    print('\nREPAIRED (%d files):' % len(repaired))
    for rel, notes in repaired[:40]:
        print('  %-58s %s' % (rel, '+'.join(notes)))
    if len(repaired) > 40:
        print('  ... and %d more' % (len(repaired) - 40))

    print('\nFRONTMATTER CHECK: %s'
          % ('ALL OK' if not bad_frontmatter else '%d BROKEN' % len(bad_frontmatter)))
    for rel, why in bad_frontmatter:
        print('  FAIL %-56s %s' % (rel, why))

    print('\nMACHINE-PATH LEAKS: %s' % ('none' if not leaks else '%d' % len(leaks)))
    seen = set()
    for rel, hit, line in leaks:
        if (rel, hit) in seen:
            continue
        seen.add((rel, hit))
        print('  %-46s %-22s %s' % (rel, hit, line))

    return 1 if (bad_frontmatter or leaks) else 0


if __name__ == '__main__':
    sys.exit(main())
