<#
.SYNOPSIS
  Write correct .cbmignore files so codebase-memory-mcp indexes source, not assets.

.DESCRIPTION
  Indexing a Skyrim mod tree without scope control produces graphs of 100,000+ nodes
  made almost entirely of vendored headers, duplicated version snapshots and binary
  assets. This script writes a per-project .cbmignore that removes all four bloat
  sources, and resolves versioned workspaces against CURRENT.txt.

  Case sensitivity: .cbmignore matching IS case-sensitive, and Skyrim capitalizes
  Meshes/Textures/Sound. Every asset rule is emitted in both cases on purpose.

  Source-carrier exception: where a project's active version is a packaged release
  with no source, the source often lives only in an older snapshot. This script
  detects that and keeps that snapshot too, rather than silently dropping the only
  copy of the code.

  Safe by default: reports what it would do. Pass -Apply to write.
  It only ever writes .cbmignore files; it never deletes or indexes anything.

.PARAMETER Path
  A project root, or a workspace root when used with -Recurse.

.PARAMETER Recurse
  Treat -Path as a workspace and process each immediate child directory as a project.

.PARAMETER Apply
  Actually write the .cbmignore files. Without this the script only reports.

.PARAMETER ExcludeName
  Child directory names to skip in -Recurse mode (archives, staging, templates).

.EXAMPLE
  .\Setup-CodebaseMemory-Index.ps1 -Path 'Z:\Work\MyMod'

.EXAMPLE
  .\Setup-CodebaseMemory-Index.ps1 -Path 'Z:\Work\AiWorkspace' -Recurse -Apply

.NOTES
  After running, index with:
    index_repository(repo_path=<project root>, mode=moderate, name=<stable-slug>)
  Then sanity-check node count against file count, and confirm languages with
  get_architecture(aspects=["languages"]).
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)][string]$Path,
    [switch]$Recurse,
    [switch]$Apply,
    [string[]]$ExcludeName = @('zOlder', '_stage', '_inspect', '.pnpm-store', '_AI-SHARED-MEMORY')
)

$ErrorActionPreference = 'Stop'

# Marker delimits the generated stale-snapshot block so re-runs are idempotent.
$marker = '# --- stale version snapshots (generated; re-run the script to refresh) ---'

$baseIgnore = @'
# .cbmignore - codebase-memory-mcp index scope.
# Generated by TOOLS/Setup-CodebaseMemory-Index.ps1
#
# MATCHING IS CASE-SENSITIVE: `meshes/` does NOT match `Meshes/`.
# Asset rules are listed in both cases on purpose - do not tidy them away.

# --- vendored dependencies and build output ---
extern/
external/
vcpkg_installed/
node_modules/
__pycache__/
.venv/
venv/
site-packages/
build/
dist/
out/
obj/
release/
packages/
.pnpm-store/

# --- Skyrim binary assets ---
meshes/
Meshes/
MESHES/
textures/
Textures/
TEXTURES/
sound/
Sound/
sounds/
Sounds/
music/
Music/
grass/
Grass/
seq/
SEQ/
Seq/
*.nif
*.NIF
*.hkx
*.HKX
*.dds
*.DDS
*.bsa
*.BSA
*.ba2
*.esp
*.ESP
*.esm
*.ESM
*.esl
*.ESL
*.pex
*.PEX
*.fuz
*.wav
*.xwm
*.tri
*.btr
*.bto
*.hkt
*.psa
*.bik
*.swf

# --- archives, binaries, images ---
*.zip
*.7z
*.rar
*.exe
*.dll
*.pdb
*.lib
*.png
*.jpg
*.jpeg
*.tga

# --- secrets: the graph is queryable, keys must not enter it ---
.env
.env.*

# --- reserved Windows device name; a stray `nul` file breaks the indexer ---
nul
'@

$vendorRe = '\\(extern|external|vcpkg_installed|node_modules|build|dist|obj|__pycache__|site-packages)\\'
$codeExt = @('.h', '.hpp', '.cpp', '.c', '.cs', '.py', '.ts', '.tsx', '.js', '.jsx',
             '.psc', '.ps1', '.go', '.rs', '.rb', '.java', '.lua', '.php', '.swift')
$compiledExt = @('.h', '.hpp', '.cpp', '.c', '.cs', '.rs', '.go')

function Measure-Source {
    param([string]$Dir, [string[]]$Ext)
    $n = @(Get-ChildItem -LiteralPath $Dir -Recurse -File -Force -ErrorAction SilentlyContinue |
           Where-Object { $Ext -contains $_.Extension.ToLower() -and $_.FullName -notmatch $vendorRe }).Count
    return $n
}

function Get-ActiveVersionName {
    param([string]$ProjectRoot, $Snapshots)
    $active = $null
    $cur = Join-Path $ProjectRoot 'CURRENT.txt'
    if (Test-Path -LiteralPath $cur) {
        $txt = (Get-Content -LiteralPath $cur -TotalCount 3 -ErrorAction SilentlyContinue) -join ' '
        $m = [regex]::Match($txt, '\d+\.\d+(\.\d+)?')
        if ($m.Success) { $active = $m.Value }
    }
    if ($active) {
        $hit = @($Snapshots | Where-Object { $_.Name -match [regex]::Escape($active) })
        if ($hit.Count -gt 0) { return [string]$hit[0].Name }
    }
    # No CURRENT.txt (or it names no existing folder): fall back to the HIGHEST
    # version, never the newest mtime - a touched old folder is not the active one.
    $sorted = @($Snapshots | Sort-Object @{ Expression = {
        $mm = [regex]::Match($_.Name, '\d+\.\d+(\.\d+)?')
        if ($mm.Success) {
            $v = $mm.Value
            $dots = ($v.ToCharArray() | Where-Object { $_ -eq '.' }).Count
            if ($dots -lt 2) { $v = $v + '.0' }
            try { [version]$v } catch { [version]'0.0.0' }
        } else { [version]'0.0.0' }
    } } -Descending)
    return [string]$sorted[0].Name
}

function Set-ProjectIgnore {
    param([string]$ProjectRoot)

    $name = Split-Path $ProjectRoot -Leaf
    $lines = $baseIgnore -split "`r?`n"

    $snapshots = @(Get-ChildItem -LiteralPath $ProjectRoot -Directory -Force -ErrorAction SilentlyContinue |
                   Where-Object { $_.Name -match '\d+\.\d+' })

    $keepName = $null
    $alsoKeep = @()
    $stale = @()

    if ($snapshots.Count -ge 2) {
        $keepName = Get-ActiveVersionName -ProjectRoot $ProjectRoot -Snapshots $snapshots
        $keepDir = Join-Path $ProjectRoot $keepName

        $keepCode = Measure-Source -Dir $keepDir -Ext $codeExt
        $keepComp = Measure-Source -Dir $keepDir -Ext $compiledExt

        # Active version may be a packaged release; find the real source carrier.
        if ($keepCode -lt 5 -or $keepComp -eq 0) {
            $useCompiled = ($keepComp -eq 0 -and $keepCode -ge 5)
            $best = $null; $bestN = 0
            foreach ($d in $snapshots) {
                if ([string]$d.Name -eq $keepName) { continue }
                if ($useCompiled) { $n = Measure-Source -Dir $d.FullName -Ext $compiledExt }
                else              { $n = Measure-Source -Dir $d.FullName -Ext $codeExt }
                if ($n -gt $bestN) { $bestN = $n; $best = [string]$d.Name }
            }
            if ($best -and $bestN -ge 5) {
                $alsoKeep += $best
                if ($useCompiled) { $why = 'active carries no compiled-language source' }
                else { $why = ("active is nearly empty (code={0})" -f $keepCode) }
                Write-V5Warn ("{0}: {1} -> also keeping '{2}' ({3} files)" -f $name, $why, $best, $bestN)
            }
        }

        $stale = @($snapshots | Where-Object {
            [string]$_.Name -ne $keepName -and $alsoKeep -notcontains [string]$_.Name })
    }

    if ($stale.Count -gt 0) {
        $lines += ''
        $lines += $marker
        $lines += ("# active = {0}" -f $keepName)
        foreach ($k in $alsoKeep) { $lines += ("# source carrier kept = {0}" -f $k) }
        foreach ($s in $stale) { $lines += ([string]$s.Name + '/') }
    }

    $target = Join-Path $ProjectRoot '.cbmignore'
    if ($Apply) {
        Set-Content -LiteralPath $target -Value $lines -Encoding UTF8
        Write-V5Ok ("{0}  (snapshots: {1} kept, {2} excluded)" -f $name, (1 + $alsoKeep.Count), $stale.Count)
    }
    else {
        Write-Host ("  WOULD WRITE  {0}  (snapshots: {1} kept, {2} excluded)" -f `
            $name, (1 + $alsoKeep.Count), $stale.Count)
    }
}

# --- main -------------------------------------------------------------------

. (Join-Path $PSScriptRoot 'V6-Common.ps1')

if (-not (Test-Path -LiteralPath $Path)) { throw "Path not found: $Path" }

Write-V5Step ("codebase-memory index scope  ->  {0}" -f $Path)
if (-not $Apply) { Write-V5Warn 'DRY RUN - no files written. Re-run with -Apply.' }

$targets = @()
if ($Recurse) {
    $targets = @(Get-ChildItem -LiteralPath $Path -Directory -Force -ErrorAction SilentlyContinue |
                 Where-Object { $ExcludeName -notcontains $_.Name -and -not $_.Name.StartsWith('.') } |
                 Select-Object -ExpandProperty FullName)
}
else {
    $targets = @($Path)
}

foreach ($t in $targets) { Set-ProjectIgnore -ProjectRoot $t }

Write-Host ''
Write-V5Step ("{0} project(s) processed" -f $targets.Count)
Write-Host '  Next: index_repository(repo_path=<root>, mode=moderate, name=<stable-slug>)'
Write-Host '  Then: check node count against file count, and confirm languages with'
Write-Host '        get_architecture(aspects=["languages"]).'
Write-Host '  Note: Papyrus (.psc) is never parsed - a tiny graph for a script-only mod is correct.'
